name: CI and Deploy

on:
  push:
    branches:
      - main  # Optional: Only trigger on push to main

jobs:
  dockerbuildpush:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

  deploy:
    needs: dockerbuildpush  # This ensures deploy happens after docker build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh-add private_key.pem

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
            docker stop webapp || true
            docker rm webapp || true
            docker run -d --name webapp -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
